// Code generated by Prismic. DO NOT EDIT.

import About from "./About";
import Hero from "./Hero";
import Listing from "./Listing";
import Media from "./Media";
import RichText from "./RichText";
import SectionIntro from "./SectionIntro";
import TextImage from "./TextImage";

export const components = {
	about: About,
	hero: Hero,
	listing: Listing,
	media: Media,
	rich_text: RichText,
	section_intro: SectionIntro,
	text_image: TextImage
};